name: Build and test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 18, 20 ]
    name: Node ${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npx next telemetry disable # https://github.com/vercel/next.js/issues/47121#issuecomment-1499044345 
      - run: npm run build
      - run: npm run test
