name: Build and test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        node-version: [ "22.17" ]
    name: Node ${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Create .env for conceptual-model-editor
        run: cp applications/conceptual-model-editor/.env.example applications/conceptual-model-editor/.env
      - name: Install packages
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
